name: add_to_gallery
description: Saves a copy of images and videos to the Android Gallery and iOS Photos
version: 0.3.0
homepage: https://github.com/flowmobile/add_to_gallery
repository: https://github.com/flowmobile/add_to_gallery

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  http: ^0.13.3
  path: ^1.8.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flowmobile.add_to_gallery
        pluginClass: AddToGalleryPlugin
      ios:
        pluginClass: AddToGalleryPlugin
