name: add_to_gallery
description: Saves a copy of images and videos to the Android Gallery and iOS Photos
version: 0.4.0+1
homepage: https://github.com/flowmobile/add_to_gallery
repository: https://github.com/flowmobile/add_to_gallery

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  path: ^1.9.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flowmobile.add_to_gallery
        pluginClass: AddToGalleryPlugin
      ios:
        pluginClass: AddToGalleryPlugin
